name: izb_ui
description: izb_ui
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  http: ^1.0.0
  dart_mappable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.3.2
  custom_lint:

  build_runner: ^2.4.4
  dart_mappable_builder: ^3.0.2

flutter:
  uses-material-design: true
